
# Exception handling ( try, except )

# print("Enter the num1\n")
# num1 = (input())
# print("Enter the num2\n")
# num2 = (input())
# try:
#     print("The sum of these two number is",
#           int(num1) + int(num2))
# except Exception as e:
#     print(e)

